title: "ARA-NODE"
baseurl: "/ARA-NODE_AI-AGENT"
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
  - scope:
      path: "sections"
      type: "pages"
    values:
      layout: default
